[AttributesSettings]
Path = 'D:\workspace\huntshowdownstats\fakeattr'
Filename = '\attributes.xml'

[Activity]
LastSavedKeyHash = 'pgool3lr9ulnneve3au96b7ap69hylm6pjbjuxa5x5ypixpb4v34ai6n7rym4xfjd8x4bydtnrr2mxeetd66mnbpmspkp43xej'
