[AttributesSettings]
Path = 'D:\workspace\huntshowdownstats\fakeattr'
Filename = '\attributes.xml'

[Activity]
LastSavedKeyHash = 'lg669d93zu544qkqn9uw2og392wt3owqg4d4smklml76t7gqx4lxmhjrz5a679tmdkj739dubggdewjji4ll2x9z2fzqz9m2op'
Reporter = 55834722896
SendReports = false
Notifications = true
