[AttributesSettings]
Path = 'D:\workspace\huntshowdownstats\fakeattr'
Filename = '\attributes.xml'

[Activity]
LastSavedKeyHash = 'n3g9depnktpenbll67u52x7keo3s5p8evllrcxdgymmpvhb2n2b4pg1yoo2k2vmfd22p9p3li2d4gy5d2fbpmg8bn2hr3xbodlximjlmjlen'
