[AttributesSettings]
Path = 'D:\steam\steamapps\common\Hunt Showdown\user\profiles\default'
Filename = '\attributes.xml'

[Activity]
LastSavedKeyHash = '5eq45gp27sr49xdz74so4ax4w2umnndgxjqc4345mr26cxwq6z3rn1nmp2mrbo0rxax2x9ask27n29okclmmwgwrdu6ddplp5bhag6kdeka'
Reporter = 55834722896
SendReports = true
