[AttributesSettings]
Path = 'C:\Users\sunsu\workspace\hunt\profile'
Filename = '\attributes.xml'

[Activity]
LastSavedKeyHash = 'pzepbwj9nfewlwxknau5bepnk2o1amm6d6jws6aaglgq9u9rmk3nr91de2b3obosr4o95pz2cb7plex7'
Reporter = 55834722896
SendReports = false
