[AttributesSettings]
Path = 'D:\steam\steamapps\common\Hunt Showdown\user\profiles\default'
Filename = '\attributes.xml'

[Activity]
LastSavedKeyHash = 'xe6x84vxtnylpd5rh3lxav6atd9krbdlx0dbbyjy45f5g7ev6g5fordbp5laska5edax5ckdngr5x2i9lx4apgyudv7brbxetaovy6ba2'
